name: Run Playwright Tests

on:
  workflow_dispatch:  # Triggered remotely by the app repo

jobs:
  trigger-test:
    runs-on: windows-latest  # Corrected runner type

    steps:
      - name: Checkout Application Repo
        uses: actions/checkout@v4  # No need for git clone since we're already using actions/checkout

      - name: Install Dependencies
        run: |
          npm install  # Installs app dependencies

      - name: Start Application (Windows)
        run: |
          Start-Process -NoNewWindow -FilePath "npm" -ArgumentList "start"  # Correct way to run npm start on Windows

      - name: Install Playwright Test Dependencies
        run: npm install @playwright/test  # Install Playwright

      - name: Run Playwright Tests
        run: npx playwright test  # Runs Playwright tests

      - name: Upload Test Report
        uses: actions/upload-artifact@v4  # Updated to the latest version
        with:
          name: playwright-report
          path: playwright-report/  # Adjust this path if needed
