name: Run Playwright Tests

on:
  workflow_dispatch:  # Triggered remotely by the app repo

jobs:
  trigger-test:
    runs-on: windows-latest
    steps:
      - name: Checkout Playwright Testing Repo
        uses: actions/checkout@v4

      # - name: Clone Application Repo
      #   run: git clone https://github.com/SickPython/playwrightapplication.git

      - name: Install Dependencies
        run: |
          cd playwrightapplication
          npm install  # Modify if needed

      - name: Start Application
        run: |
          cd playwrightapplication
          npm start &  # Runs app in background

      - name: Install Playwright
        run: npm install @playwright/test

      - name: Run Playwright Tests
        run: npx playwright test

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/
